// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Toaster } from "sonner";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
<<<<<<< HEAD
// Proteção de rotas movida para middleware
import { MigrationHelper } from "@/components/MigrationHelper";
=======
import { ProtectedRoute } from "@/components/custom/ProtectedRoute";
>>>>>>> d39087cde5feec399230e3e6916840f20a10d4e4

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MindFix - Domine seu foco e conquiste seus objetivos",
  description: "O app definitivo para foco, produtividade e gestão de atenção. Técnicas científicas para TDAH e hiperfoco.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <Script src="/suppress-supabase-errors.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <MigrationHelper />
        {children}
=======
        <ProtectedRoute>
          {children}
        </ProtectedRoute>
>>>>>>> d39087cde5feec399230e3e6916840f20a10d4e4
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
